version: '3.4'

services:
  backend:
    image: todoapp
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
    command: ["bun", "start"]
